# kubeadm-config.yaml
kind: ClusterConfiguration
apiVersion: kubeadm.k8s.io/v1beta4
networking:
  serviceSubnet: 10.97.0.0/16
  podSubnet: 10.245.0.0/16
  dnsDomain: cluster.local
kubernetesVersion: v1.34.3
controlPlaneEndpoint: ${CLUSTER_PREFIX}-mstr-priv.clemenslabs.com
---
kind: KubeletConfiguration
apiVersion: kubelet.config.k8s.io/v1beta1
cgroupDriver: systemd
